using Pixelbyte.CodeGen;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Template_parser
{
    static class Program
    {
        static void Main()
        {

            const string constTemplate = @"//
//This file was auto-generated by Simplate
//Your changes will be changed. You have been warned...
//
public static class {{ className }}
{
	{{foreach item in items}}
	public const string {{ pascal(item) }} = ""{{ item }}"";
	{{end foreach}}
}";
            Simplate tk = Simplate.Compile(constTemplate);

            var items = new string[] { "green", "blue", "red", "black", "elvis" };
            var functors = new Functors();
            functors.Add("camel", new Func<string, string>(StringExtensions.ToCamelCase));
            functors.Add("pascal", new Func<string, string>(StringExtensions.ToPascalCase));
            functors.Add("test", new Func<string, string>(Program.Test));
            var para = new Dictionary<string, object>();
            para.Add("items", items);
            para.Add("className", "Tests");
            Console.WriteLine(tk.GetOutput(para, functors));

            using (StreamWriter sw = new StreamWriter(@"E:\test.txt"))
            {
                sw.Write(tk.GetOutput(para, functors));
            }
        }

        public static string Test(string input)
        {
            return input + "-+=";
        }
    }
}
